---
apiVersion: v1
kind: Secret
metadata:
  name: trino-s3-credentials
  namespace: industrial-iot
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minio-secret-key-change-me
