---
apiVersion: v1
kind: Service
metadata:
  name: automq-broker
  namespace: industrial-iot
  labels:
    app: automq
    component: broker
spec:
  type: ClusterIP
  selector:
    app: automq
    component: broker
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: automq-broker-headless
  namespace: industrial-iot
  labels:
    app: automq
    component: broker
spec:
  clusterIP: None
  selector:
    app: automq
    component: broker
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
