---
apiVersion: v1
kind: Service
metadata:
  name: automq-controller-headless
  namespace: industrial-iot
  labels:
    app: automq
    component: controller
spec:
  clusterIP: None
  selector:
    app: automq
    component: controller
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
