---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: industrial-iot
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: rootPassword
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for MinIO to be ready..."
              until mc alias set local http://minio.industrial-iot.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"; do
                echo "MinIO not ready, retrying in 5s..."
                sleep 5
              done
              echo "Creating buckets..."
              mc mb --ignore-existing local/automq-data
              mc mb --ignore-existing local/process-archive
              echo "Buckets created successfully."
  backoffLimit: 10
