---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: monitoring
type: Opaque
data:
  # admin-password: influxdb-admin-password
  admin-password: aW5mbHV4ZGItYWRtaW4tcGFzc3dvcmQ=
  # admin-token: influxdb-admin-token-change-me
  admin-token: aW5mbHV4ZGItYWRtaW4tdG9rZW4tY2hhbmdlLW1l
