---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-rocksdb
  namespace: industrial-iot
  labels:
    app: nessie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
